find_program(ZIG_EXECUTABLE NAMES zig REQUIRED)
set(ZIG_TARGET "x86_64-windows-gnu")

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 "cc")
set(CMAKE_CXX_COMPILER_ARG1 "c++")

set(CMAKE_C_FLAGS "--target=${ZIG_TARGET}")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_C_FLAGS}")
