find_program(ZIG_EXECUTABLE NAMES zig REQUIRED)
set(ZIG_TARGET "aarch64-macos")

execute_process(
  COMMAND xcrun --sdk macosx --show-sdk-path
  OUTPUT_VARIABLE MACOS_SYSROOT
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(CMAKE_SYSROOT "${MACOS_SYSROOT}")

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 "cc")
set(CMAKE_CXX_COMPILER_ARG1 "c++")

set(CMAKE_C_FLAGS "--target=${ZIG_TARGET} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_C_FLAGS}")
